#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: spark-pvc-rwx
#  namespace: {{ .Values.deploymentPrefix }}-portal
#spec:
#  accessModes:
#    - ReadWriteMany
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: {{ .Values.storage.defaultStorageClass }}
