apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: {{ .Values.deploymentPrefix }}-portal
  labels:
    app: spark-master
spec:
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
  - name: spark
    port: 7077
    targetPort: 7077
  - name: spark-rest
    port: 6066
    targetPort: 6066   
  - name: spark-driverui
    port: 4040
    targetPort: 4040       
  selector:
    app: spark-master

---

apiVersion: v1
kind: Service
metadata:
  name: spark-driver
  namespace: {{ .Values.deploymentPrefix }}-portal
  labels:
    app: spark-driver
spec:
  ports:
  - name: webui
    port: 4040
    targetPort: 4040    
  selector:
    app: spark-driver
  type: ClusterIP
  clusterIP: None