apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: spark-worker
  name: spark-worker
  namespace: {{ .Values.deploymentPrefix }}-portal
spec:
  replicas: 0
  selector:
    matchLabels:
      name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      imagePullSecrets:
        - name: registrycredentials
      volumes:
        - name: spark-common
          persistentVolumeClaim:
            claimName: spark-pvc-rwx   
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: spark-config
        - name: spark-defaults-share
          emptyDir: {}                             
      initContainers:
      - name: init-spark-master
        image: busybox:1.28.4
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP          
        command: ['sh', '-c', 
          'until nc -zv -w2 spark-master 7077; do echo waiting for spark-master; sleep 2; done; 
          /configmap-volume/process-spark-defaults-template.conf.sh > /opt/spark/conf/spark-defaults.conf']
        volumeMounts:
        - name: configmap-volume
          mountPath: /configmap-volume                                
        - name: spark-defaults-share
          mountPath: /opt/spark/conf                             
      containers:
      - name: spark-worker
        image: {{ .Values.imageCredentials.registry }}temenos/analytics/spark:2.4.3-0.0.2
        imagePullPolicy : "IfNotPresent"     
        ports:
        - containerPort: 8081
          protocol: TCP
          name: webui
        env:
        - name: SPARK_LOGGING_LEVEL
          value: "{{ .Values.loggingLevel.spark }}"            
        command:
        - "/bin/bash"
        - "-c"
        - "--"
        args : ["/start-worker.sh; sleep infinity"]
        resources:
          limits:
            cpu: "2.5"
            memory: 2.5Gi
          # requests:
          #  cpu: "2.5"
          #  memory: 3Gi
        volumeMounts:
        - mountPath: "/usr/lib/htrunk"
          name: spark-common    
        - name: spark-defaults-share
          mountPath: /opt/spark/conf/spark-defaults.conf
          subPath: spark-defaults.conf                   