apiVersion: v1
kind: Service
metadata:
  name: spark-ui-proxy
  namespace: {{ .Values.deploymentPrefix }}-portal
spec:
  selector:
    component: spark-ui-proxy
  ports:
  - protocol: TCP
    targetPort: 80
    port: 31101
    nodePort: 31101
  type: NodePort
