
{{ if eq .Values.storage.provider "localhost-linux" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume1
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/k8s/vol1"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume2
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/vol2"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume3
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/vol3"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume4
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/vol4"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume5
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/vol5"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume6
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/vol6"

{{ end }}