-- Create T24 base table for DES docker DEV environment

CREATE TABLE IF NOT EXISTS  TAFJ_VOC (
    RECID                     VARCHAR2(255) NOT NULL, 
    XMLRECORD                 VARCHAR2(2147483647),
    ORCLFILENAME              VARCHAR2(300),
    ORCLDICTNAME              VARCHAR2(300),
    ISBLOB                    VARCHAR2(1),
    ISRIGHTJUSTIFIED          VARCHAR2(1),
    ISREADONLY                VARCHAR2(1),
    ASSOCIATED                VARCHAR2(70),
    PDATEALIAS                VARCHAR2(70),
    OTHERATTRIBUTES           VARCHAR2(4000),
    TABLEID                   INTEGER NOT NULL,
    CONSTRAINT TAFJ_VOC_PK    PRIMARY KEY (RECID),
    CONSTRAINT TAFJ_VOC_UNIQUE UNIQUE (TABLEID)
);
--Insert into TAFJ_VOC (RECID,ORCLFILENAME, ORCLDICTNAME, ISBLOB, ISRIGHTJUSTIFIED, ISREADONLY, ASSOCIATED, PDATEALIAS, OTHERATTRIBUTES, TABLEID) values ('F.IF.INTEGRATION.FLOW.CATALOG', 'F_IF_INTEGRATION_FL002', 'D_F_IF_INTEGRATION_001', 'X', 'N', 'N', null, null, null, 1);
--Insert into TAFJ_VOC (RECID,ORCLFILENAME, ORCLDICTNAME, ISBLOB, ISRIGHTJUSTIFIED, ISREADONLY, ASSOCIATED, PDATEALIAS, OTHERATTRIBUTES, TABLEID) values ('F.DATA.EVENTS', 'F_DATA_EVENTS', null, 'X', 'N', 'N', null, null, null, 2);
--Insert into TAFJ_VOC (RECID,ORCLFILENAME, ORCLDICTNAME, ISBLOB, ISRIGHTJUSTIFIED, ISREADONLY, ASSOCIATED, PDATEALIAS, OTHERATTRIBUTES, TABLEID) values ('F.DATA.EVENTS.ILP', 'F_DATA_EVENTS_ILP', null, 'X', 'N', 'N', null, null, null, 3);

CREATE TABLE IF NOT EXISTS F_IF_INTEGRATION_FL002 (
    RECID                     VARCHAR2(255) NOT NULL,
    XMLRECORD                 VARCHAR2(2147483647),
    CONSTRAINT F_IF_INTEGRATION_FL002_PK PRIMARY KEY (RECID)
);

CREATE TABLE IF NOT EXISTS  F_RR_XSD_EVENTS (
    RECID                     VARCHAR2(255) NOT NULL,
    XMLRECORD                 VARCHAR2(2147483647) NOT NULL,
    CONSTRAINT F_RR_XSD_EVENTS_PK PRIMARY KEY (RECID)
);

CREATE TABLE IF NOT EXISTS F_FILE_CONTROL (
    RECID                     VARCHAR2(255) NOT NULL,
    XMLRECORD                 VARCHAR2(2147483647) NOT NULL,
    CONSTRAINT F_FILE_CONTROL_PK PRIMARY KEY (RECID)
);
