{{ if eq .Values.clusterSizing.deployIgnite true }}
apiVersion: v1
kind: Secret
metadata:
  name: registrycredentials
  namespace: ignite
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}