{{ if eq .Values.clusterSizing.deployIgnite true }}
kind: Service
apiVersion: v1
metadata:
  name: ignite
  namespace: ignite
spec:
  selector:
    app: ignite
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: sql
      port: 10800
      targetPort: 10800
    - name: thinclients
      port: 10900
      targetPort: 10900
  # Optional - remove 'sessionAffinity' property if the Ignite cluster
  # and applications deployed within Kubernetes
  # sessionAffinity: ClientIP

---

kind: Service
apiVersion: v1
metadata:
  name: ignite-external
  namespace: ignite
spec:
  selector:
    app: ignite
  ports:
    - name: sql
      protocol: TCP
      targetPort: 10800
      port: {{ .Values.network.igniteOutsidePort }}
      nodePort: {{ .Values.network.igniteOutsidePort }}
  type: NodePort
{{ end }}