apiVersion: v1
kind: Secret
metadata:
  name: t24-secrets
  namespace: {{ .Values.deploymentPrefix }}-t24
data:
  db_password: {{ .Values.t24db.password  | b64enc }}
  AMQ_PASSWORD: {{ .Values.amq.password  | b64enc }}
  AMQ_USER: {{ .Values.amq.user  | b64enc }}
