kind: ConfigMap
apiVersion: v1
metadata:
  name: t24-app-config
  namespace: {{ .Values.deploymentPrefix }}-t24
data:
  DB_URL: {{ .Values.t24db.url }}
  DB_USER: {{ .Values.t24db.user }}
  JMS_URL: {{ .Values.amq.broker }}