apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphite-pv-claim
  namespace: {{ .Values.deploymentPrefix }}-graphite
  labels:
    app: graphite
spec:
  storageClassName: {{ .Values.storage.defaultStorageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi