apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: {{ .Values.deploymentPrefix }}-portal
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: spark-role
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spark-role-binding
subjects:
- kind: ServiceAccount
  name: spark-sa
  namespace: {{ .Values.deploymentPrefix }}-portal
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-submit
  labels:
    origin: temenos
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - watch
      - create
      - delete
      - get

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portal-spark-submit
  labels:
    origin: temenos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-submit
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.deploymentPrefix }}-portal
