---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-labeller
  namespace: {{ .Values.deploymentPrefix }}-atlas
  labels:
    origin: apache-atlas
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atlas-pod-labler
  namespace: {{ .Values.deploymentPrefix }}-atlas
  labels:
    origin: apache-atlas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-labeller
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.deploymentPrefix }}-atlas
