apiVersion: v1
kind: Service
metadata:
  name: atlas-headless
  namespace: {{ $.Values.deploymentPrefix }}-atlas
  labels:
    app.kubernetes.io/name: atlas
    helm.sh/chart: atlas
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: atlas
    app.kubernetes.io/instance: {{ .Release.Name }}
