apiVersion: v1
kind: Secret
metadata:
  name: ignite-keystore-password
  namespace: des
data:
  password: {{ .Values.des.keystore.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: jdbc-password
  namespace: des
data:
  password: {{ .Values.des.temenosTafjJdbcPwd | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: jdbc-eventerrorcache-password
  namespace: des
data:
  password: {{ .Values.des.temenosTafjJdbcErrorCachePwd | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: jdbc-eventcache-password
  namespace: des
data:
  password: {{ .Values.des.temenosTafjJdbcEventCachePwd | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: jdbc-eventxsdcache-password
  namespace: des
data:
  password: {{ .Values.des.temenosTafjJdbcXsdEventCachePwd | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: eventhub-shared-key
  namespace: des
data:
  sharedkey: {{ .Values.des.eventHubSharedAccessKey | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: eventhub-ilp-shared-key
  namespace: des
data:
  sharedkey: {{ .Values.des.eventHubSharedAccessIlpKey | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: eventhubforschema-shared-key
  namespace: des
data:
  sharedkey: {{ .Values.des.eventHubSharedAccessKeyForSchema | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: des
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
