{{ if eq .Values.clusterSizing.deployMssql true }}
apiVersion: v1
kind: Secret
metadata:
  name: registrycredentials
  namespace: {{ .Values.deploymentPrefix }}-mssql
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}