{{ if eq .Values.clusterSizing.deployMssql true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql
  namespace: {{ .Values.deploymentPrefix }}-mssql

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mssql
  namespace: {{ .Values.deploymentPrefix }}-mssql
rules:
- apiGroups:
  - ""
  resources: # Here are resources you can access
  - pods
  - endpoints
  verbs: # That is what you can do with them
  - get
  - list
  - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mssql
roleRef:
  kind: ClusterRole
  name: mssql
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: mssql
  namespace: {{ .Values.deploymentPrefix }}-mssql
{{ end }}