apiVersion: v1
kind: Secret
metadata:
  name: registrycredentials
  namespace: {{ .Values.deploymentPrefix }}-grafana
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}