apiVersion: v1
kind: Service
metadata:
  name: grafana-outside
  namespace: {{ .Values.deploymentPrefix }}-grafana
spec:
  selector:
    app: grafana
  ports:
  - name: http-outside
    protocol: TCP
    port: {{ .Values.network.grafanaOutsidePort }}
    {{ if eq .Values.network.portal.portalOutsideServiceType "NodePort" }}
    nodePort: {{ .Values.network.grafanaOutsidePort }}
    {{ end }}
    targetPort: 3000
  type: {{ .Values.network.portal.portalOutsideServiceType }}

---

kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: {{ .Values.deploymentPrefix }}-grafana
spec:
  selector:
    app: grafana
  ports:
  - name: http-inside
    protocol: TCP
    port: 3000


---  