apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc-rwx
  namespace: {{ .Values.deploymentPrefix }}-portal
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.sparkShareSize }}
  storageClassName: {{ .Values.storage.defaultSharedStorageClass }}
