---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-labeller
  namespace: {{ .Values.deploymentPrefix }}-mysql
  labels:
    origin: temenos-mysql
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-pod-labler
  namespace: {{ .Values.deploymentPrefix }}-mysql
  labels:
    origin: temenos-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-labeller
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.deploymentPrefix }}-mysql
