apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: {{ .Values.deploymentPrefix }}-mysql
  labels:
    app: mysql
spec:
  storageClassName: {{ .Values.storage.defaultStorageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi