kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
  name: azure-disk-premium
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  kind: managed
  location: {{ .Values.storage.azure.storageLocation }}
  storageAccountType: Premium_LRS

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
  name: azure-file-premium
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
parameters:
  location: {{ .Values.storage.azure.storageLocation }}

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer